<template><div><h1 id="change-log" tabindex="-1"><a class="header-anchor" href="#change-log" aria-hidden="true">#</a> Change Log</h1>
<p>Track new features, any breaking changes, and the release history here.</p>
<h2 id="articles" tabindex="-1"><a class="header-anchor" href="#articles" aria-hidden="true">#</a> Articles</h2>
<h3 id="_18-07-2023-what-s-new-in-murex-v4-4" tabindex="-1"><a class="header-anchor" href="#_18-07-2023-what-s-new-in-murex-v4-4" aria-hidden="true">#</a> 18.07.2023 - <RouterLink to="/changelog/v4.4.html">What's new in murex v4.4</RouterLink></h3>
<p>v4.4 features two new builtins, improvements in testing, and automatic generation of autocompletion suggestions backed by man page parsing. Plus there has been a lot of focus on improving <em>readline</em> responsiveness</p>
<h3 id="_02-07-2023-what-s-new-in-murex-v4-3" tabindex="-1"><a class="header-anchor" href="#_02-07-2023-what-s-new-in-murex-v4-3" aria-hidden="true">#</a> 02.07.2023 - <RouterLink to="/changelog/v4.3.html">What's new in murex v4.3</RouterLink></h3>
<p>This brings improved support on Windows plus one breaking change from the previous release (v4.2)</p>
<h3 id="_19-06-2023-what-s-new-in-murex-v4-2" tabindex="-1"><a class="header-anchor" href="#_19-06-2023-what-s-new-in-murex-v4-2" aria-hidden="true">#</a> 19.06.2023 - <RouterLink to="/changelog/v4.2.html">What's new in murex v4.2</RouterLink></h3>
<p>Murex usage has raised considerably in recent weeks. This release addresses a number of feature requests and bugs raised on Github.</p>
<h3 id="_04-06-2023-what-s-new-in-murex-v4-1-x" tabindex="-1"><a class="header-anchor" href="#_04-06-2023-what-s-new-in-murex-v4-1-x" aria-hidden="true">#</a> 04.06.2023 - <RouterLink to="/changelog/v4.1.html">What's new in murex v4.1.x</RouterLink></h3>
<p>The previous releases have brought significant advancements to Murex's syntax but at the cost of longer gaps between releases. So the 4.1.x versions will be shorter releases but focusing on bug fixes. The 4.1.x release notes will be appended to <a href="https://murex.rocks/changelog/" target="_blank" rel="noopener noreferrer">murex.rocks changelog<ExternalLinkIcon/></a> and available on <a href="https://github.com/lmorg/murex/releases" target="_blank" rel="noopener noreferrer">Github releases<ExternalLinkIcon/></a> too</p>
<h3 id="_26-03-2023-what-s-new-in-murex-v4-0" tabindex="-1"><a class="header-anchor" href="#_26-03-2023-what-s-new-in-murex-v4-0" aria-hidden="true">#</a> 26.03.2023 - <RouterLink to="/changelog/v4.0.html">What's new in murex v4.0</RouterLink></h3>
<p>This release sees significant improvements for use with non-latin characters in both the interactive prompt and shell scripting. It introduces new syntax to make working with structured data even easier than before. As well as new data types and smoother user experience.</p>
<h3 id="_12-02-2023-what-s-new-in-murex-v3-1" tabindex="-1"><a class="header-anchor" href="#_12-02-2023-what-s-new-in-murex-v3-1" aria-hidden="true">#</a> 12.02.2023 - <RouterLink to="/changelog/v3.1.html">What's new in murex v3.1</RouterLink></h3>
<p>This release includes mostly bug fixes and new experimental features which are opt into. To enable all experimental features, set the environmental variable <code v-pre>MUREX_EXPERIMENTAL</code> to any value. Or you can enable specific features individually via `config</p>
<h3 id="_31-12-2022-what-s-new-in-murex-v3-0" tabindex="-1"><a class="header-anchor" href="#_31-12-2022-what-s-new-in-murex-v3-0" aria-hidden="true">#</a> 31.12.2022 - <RouterLink to="/changelog/v3.0.html">What's new in murex v3.0</RouterLink></h3>
<p>This is a major release that brings a significant number of changes and improvements, including a complete overhaul of the parser. Backwards compatibility is a high priority however these new features bring greater readability and consistency to shell scripting. So while the older syntax remains for compatibility, it is worth migrating over to the newer syntax for all new code being written</p>
<h3 id="_12-09-2022-what-s-new-in-murex-v2-11" tabindex="-1"><a class="header-anchor" href="#_12-09-2022-what-s-new-in-murex-v2-11" aria-hidden="true">#</a> 12.09.2022 - <RouterLink to="/changelog/v2.11.html">What's new in murex v2.11</RouterLink></h3>
<p>This release mainly focuses on refinements in performance and usability, rather than introducing new features</p>
<h3 id="_01-08-2022-what-s-new-in-murex-v2-10" tabindex="-1"><a class="header-anchor" href="#_01-08-2022-what-s-new-in-murex-v2-10" aria-hidden="true">#</a> 01.08.2022 - <RouterLink to="/changelog/v2.10.html">What's new in murex v2.10</RouterLink></h3>
<p>This release brings a few minor improvements and bug fixes rather than big new headline features.</p>
<h3 id="_15-07-2022-what-s-new-in-murex-v2-9" tabindex="-1"><a class="header-anchor" href="#_15-07-2022-what-s-new-in-murex-v2-9" aria-hidden="true">#</a> 15.07.2022 - <RouterLink to="/changelog/v2.9.html">What's new in murex v2.9</RouterLink></h3>
<p>This release focuses on testing and REPL usability improvements but also includes updates several new run modes to make error handling easier in larger scripts.</p>
<h3 id="_23-05-2022-what-s-new-in-murex-v2-8" tabindex="-1"><a class="header-anchor" href="#_23-05-2022-what-s-new-in-murex-v2-8" aria-hidden="true">#</a> 23.05.2022 - <RouterLink to="/changelog/v2.8.html">What's new in murex v2.8</RouterLink></h3>
<p>This release comes with a number of experimental but stable features that might eventually become standard practice. The features are there to use if you with but adjacent from the older code so there is zero risk in updating to this version.</p>
<h3 id="_15-05-2022-what-s-new-in-murex-v2-7" tabindex="-1"><a class="header-anchor" href="#_15-05-2022-what-s-new-in-murex-v2-7" aria-hidden="true">#</a> 15.05.2022 - <RouterLink to="/changelog/v2.7.html">What's new in murex v2.7</RouterLink></h3>
<p>This update has introduced another potential breaking change for your safety: zero length arrays now fail by default. Also errors inside subshells will cause the parent command to fail if ran inside a <code v-pre>try</code> or <code v-pre>trypipe</code> block.</p>
<h3 id="_26-02-2022-what-s-new-in-murex-v2-6" tabindex="-1"><a class="header-anchor" href="#_26-02-2022-what-s-new-in-murex-v2-6" aria-hidden="true">#</a> 26.02.2022 - <RouterLink to="/changelog/v2.6.html">What's new in murex v2.6</RouterLink></h3>
<p>This update has introduced a potential breaking change: variables now need to be defined before usage otherwise the commandline will fail. Read notes to learn how to disable this feature where needed. Also included in this release is the <code v-pre>select</code> command as part of the standard build.</p>
<h3 id="_12-02-2022-what-s-new-in-murex-v2-5" tabindex="-1"><a class="header-anchor" href="#_12-02-2022-what-s-new-in-murex-v2-5" aria-hidden="true">#</a> 12.02.2022 - <RouterLink to="/changelog/v2.5.html">What's new in murex v2.5</RouterLink></h3>
<p>This release introduces a number of new builtins, fixes some regression bugs and supercharges the <code v-pre>select</code> optional builtin (which I plan to include into the core builtins for non-Windows users in the next release).</p>
<h3 id="_09-12-2021-what-s-new-in-murex-v2-4" tabindex="-1"><a class="header-anchor" href="#_09-12-2021-what-s-new-in-murex-v2-4" aria-hidden="true">#</a> 09.12.2021 - <RouterLink to="/changelog/v2.4.html">What's new in murex v2.4</RouterLink></h3>
<p>This release introduces a strict mode for variables, new builtin, performance improvements, and better error messages; plus a potential breaking change</p>
<h3 id="_26-09-2021-what-s-new-in-murex-v2-3" tabindex="-1"><a class="header-anchor" href="#_26-09-2021-what-s-new-in-murex-v2-3" aria-hidden="true">#</a> 26.09.2021 - <RouterLink to="/changelog/v2.3.html">What's new in murex v2.3</RouterLink></h3>
<p>This release includes significant changes to the interactive terminal</p>
<h3 id="_21-06-2021-what-s-new-in-murex-v2-2" tabindex="-1"><a class="header-anchor" href="#_21-06-2021-what-s-new-in-murex-v2-2" aria-hidden="true">#</a> 21.06.2021 - <RouterLink to="/changelog/v2.2.html">What's new in murex v2.2</RouterLink></h3>
<p>This is mainly a bug fix release but it does include one breaking change for <code v-pre>config</code>. Please read for details.</p>
<h3 id="_30-04-2021-what-s-new-in-murex-v2-1" tabindex="-1"><a class="header-anchor" href="#_30-04-2021-what-s-new-in-murex-v2-1" aria-hidden="true">#</a> 30.04.2021 - <RouterLink to="/changelog/v2.1.html">What's new in murex v2.1</RouterLink></h3>
<p>This release comes with support for inlining SQL and some major bug fixes plus a breaking change for <code v-pre>config</code>. Please read for details.</p>
<h3 id="_17-04-2021-what-s-new-in-murex-v2-0" tabindex="-1"><a class="header-anchor" href="#_17-04-2021-what-s-new-in-murex-v2-0" aria-hidden="true">#</a> 17.04.2021 - <RouterLink to="/changelog/v2.0.html">What's new in murex v2.0</RouterLink></h3>
<p>This release comes with spellchecking, inlined images, smarter syntax completion and more</p>
</div></template>


