package docs

// This file was generated from [builtins/core/management/which_doc.yaml](https://github.com/lmorg/murex/blob/master/builtins/core/management/which_doc.yaml).

func init() {

	Definition["which"] = "# `which`\n\n> Locate command origin\n\n## Description\n\n`which` locates a command's origin. If STDOUT is a TTY, then it's output will be\nhuman readable. If STDOUT is a pipe then it's output will be a simple list.\n\n`which` can take multiple parameters, each representing a different command you\nwant looked up.\n\n## Usage\n\n```\nwhich command... -> <stdout>\n```\n\n## Examples\n\n**TTY output:**\n\n```\n» which cat dog jobs git dug\ncat => (/bin/cat) cat - concatenate and print files\ndog => unknown\njobs => (alias) fid-list --jobs => (builtin) Lists all running functions within the current Murex session\ngit => (/opt/homebrew/bin/git -> ../Cellar/git/2.41.0/bin/git) git - the stupid content tracker\ndug => (murex function) A bit like dig but which outputs JSON\n```\n\n**Piped output:**\n\n```\n» which cat dog jobs git dug -> cat\n/bin/cat\nunknown\nalias\n/opt/homebrew/bin/git\nfunction\n```\n\n## Detail\n\nThere are a few different types of commands:\n\n### alias\n\nThis will be represented in `which` by the term `alias` and, when STDOUT is a\nTTY, `which` will follow the alias to print what command the alias points to.\n\n### function\n\nThis is a Murex function (defined via `function`) and will be represented in\n`which` by the term `function`.\n\n### builtin\n\nThis is a shell builtin, like `out` and `exit`. It will be represented in\n`which` by the term `builtin`.\n\n### external executable\n\nThis is any other external command, such as `systemctl` and `python`. This\nwill be represented in `which` by the path to the executable. When STDOUT is a\nTTY, `which` will also print the destination path of any symlinks too.\n\n## See Also\n\n* [`alias`](../commands/alias.md):\n  Create an alias for a command\n* [`exec`](../commands/exec.md):\n  Runs an executable\n* [`exit`](../commands/exit.md):\n  Exit murex\n* [`fexec` ](../commands/fexec.md):\n  Execute a command or function, bypassing the usual order of precedence.\n* [`function`](../commands/function.md):\n  Define a function block\n* [`out`](../commands/out.md):\n  Print a string to the STDOUT with a trailing new line character\n* [type](../commands/type.md):\n  \n\n<hr/>\n\nThis document was generated from [builtins/core/management/which_doc.yaml](https://github.com/lmorg/murex/blob/master/builtins/core/management/which_doc.yaml)."

}
