codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1
    wait_for_ci: false

coverage:
  status:
    patch: off
    project:
      default:
#        target: 70
        threshold: 1%
        if_ci_failed: success
      docgen:
        paths:
          - tools/docgen
      readline:
        paths:
          - utils/readline
      wasmserver:
        paths:
          - utils/wasmserver

ignore:
  - "vendor"                # not my project files
  - "builtins/import_build" # these should just be copies of import_src
  - "**/*_test.go"          # Go test files (you shouldn't test test files)
  - "**/*.mx"               # these are tested outside of codecov
  - "**/*.sh"               # these are just for bootstrapping development
  - "**/*.test"             # files generated for testing
  - "utils/docgen"          # this is a separate project for bootstrapping development
  - "utils/wasmserver"      # this is also a separate project for bootstrapping development