// Code generated by "stringer -type=PipeToken"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PipeTokenNone-0]
	_ = x[PipeTokenPosix-1]
	_ = x[PipeTokenArrow-2]
	_ = x[PipeTokenGeneric-3]
	_ = x[PipeTokenRedirect-4]
	_ = x[PipeTokenAppend-5]
}

const _PipeToken_name = "PipeTokenNonePipeTokenPosixPipeTokenArrowPipeTokenGenericPipeTokenRedirectPipeTokenAppend"

var _PipeToken_index = [...]uint8{0, 13, 27, 41, 57, 74, 89}

func (i PipeToken) String() string {
	if i < 0 || i >= PipeToken(len(_PipeToken_index)-1) {
		return "PipeToken(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PipeToken_name[_PipeToken_index[i]:_PipeToken_index[i+1]]
}
