// Code generated by "stringer -type=Property"; DO NOT EDIT.

package functions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[P_NEW_CHAIN-1]
	_ = x[P_METHOD-2]
	_ = x[P_FOLLOW_ON-4]
	_ = x[P_PIPE_OUT-8]
	_ = x[P_PIPE_ERR-16]
	_ = x[P_LOGIC_AND-32]
	_ = x[P_LOGIC_OR-64]
}

const (
	_Property_name_0 = "P_NEW_CHAINP_METHOD"
	_Property_name_1 = "P_FOLLOW_ON"
	_Property_name_2 = "P_PIPE_OUT"
	_Property_name_3 = "P_PIPE_ERR"
	_Property_name_4 = "P_LOGIC_AND"
	_Property_name_5 = "P_LOGIC_OR"
)

var (
	_Property_index_0 = [...]uint8{0, 11, 19}
)

func (i Property) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Property_name_0[_Property_index_0[i]:_Property_index_0[i+1]]
	case i == 4:
		return _Property_name_1
	case i == 8:
		return _Property_name_2
	case i == 16:
		return _Property_name_3
	case i == 32:
		return _Property_name_4
	case i == 64:
		return _Property_name_5
	default:
		return "Property(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
