// Code generated by "stringer -type=RunMode"; DO NOT EDIT.

package runmode

import "strconv"

const _RunMode_name = "ShellNormalTryTryPipeEvil"

var _RunMode_index = [...]uint8{0, 5, 11, 14, 21, 25}

func (i RunMode) String() string {
	if i < 0 || i >= RunMode(len(_RunMode_index)-1) {
		return "RunMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunMode_name[_RunMode_index[i]:_RunMode_index[i+1]]
}
