// Code generated by "stringer -type=fFlagsT"; DO NOT EDIT.

package io

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fFile-1]
	_ = x[fDirectory-2]
	_ = x[fSymlink-4]
	_ = x[fDevBlock-8]
	_ = x[fDevChar-16]
	_ = x[fSocket-32]
	_ = x[fNamedPipe-64]
	_ = x[fUserRead-128]
	_ = x[fGroupRead-256]
	_ = x[fOtherRead-512]
	_ = x[fUserWrite-1024]
	_ = x[fGroupWrite-2048]
	_ = x[fOtherWrite-4096]
	_ = x[fUserExec-8192]
	_ = x[fGroupExec-16384]
	_ = x[fOtherExec-32768]
	_ = x[fSetUid-65536]
	_ = x[fSetGid-131072]
	_ = x[fSticky-262144]
	_ = x[fIrregular-524288]
	_ = x[fHelp-1048576]
}

const _fFlagsT_name = "fFilefDirectoryfSymlinkfDevBlockfDevCharfSocketfNamedPipefUserReadfGroupReadfOtherReadfUserWritefGroupWritefOtherWritefUserExecfGroupExecfOtherExecfSetUidfSetGidfStickyfIrregularfHelp"

var _fFlagsT_map = map[fFlagsT]string{
	1:       _fFlagsT_name[0:5],
	2:       _fFlagsT_name[5:15],
	4:       _fFlagsT_name[15:23],
	8:       _fFlagsT_name[23:32],
	16:      _fFlagsT_name[32:40],
	32:      _fFlagsT_name[40:47],
	64:      _fFlagsT_name[47:57],
	128:     _fFlagsT_name[57:66],
	256:     _fFlagsT_name[66:76],
	512:     _fFlagsT_name[76:86],
	1024:    _fFlagsT_name[86:96],
	2048:    _fFlagsT_name[96:107],
	4096:    _fFlagsT_name[107:118],
	8192:    _fFlagsT_name[118:127],
	16384:   _fFlagsT_name[127:137],
	32768:   _fFlagsT_name[137:147],
	65536:   _fFlagsT_name[147:154],
	131072:  _fFlagsT_name[154:161],
	262144:  _fFlagsT_name[161:168],
	524288:  _fFlagsT_name[168:178],
	1048576: _fFlagsT_name[178:183],
}

func (i fFlagsT) String() string {
	if str, ok := _fFlagsT_map[i]; ok {
		return str
	}
	return "fFlagsT(" + strconv.FormatInt(int64(i), 10) + ")"
}
