// Code generated by "stringer -type=fFlagsT"; DO NOT EDIT.

package io

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fFile-1]
	_ = x[fDirectory-2]
	_ = x[fSymlink-4]
	_ = x[fDevBlock-8]
	_ = x[fDevChar-16]
	_ = x[fSocket-32]
	_ = x[fNamedPipe-64]
	_ = x[fIrregular-128]
	_ = x[fUserRead-256]
	_ = x[fGroupRead-512]
	_ = x[fOtherRead-1024]
	_ = x[fUserWrite-2048]
	_ = x[fGroupWrite-4096]
	_ = x[fOtherWrite-8192]
	_ = x[fUserExec-16384]
	_ = x[fGroupExec-32768]
	_ = x[fOtherExec-65536]
	_ = x[fSetUid-131072]
	_ = x[fSetGid-262144]
	_ = x[fSticky-524288]
	_ = x[fHelp-1048576]
}

const _fFlagsT_name = "fFilefDirectoryfSymlinkfDevBlockfDevCharfSocketfNamedPipefIrregularfUserReadfGroupReadfOtherReadfUserWritefGroupWritefOtherWritefUserExecfGroupExecfOtherExecfSetUidfSetGidfStickyfHelp"

var _fFlagsT_map = map[fFlagsT]string{
	1:       _fFlagsT_name[0:5],
	2:       _fFlagsT_name[5:15],
	4:       _fFlagsT_name[15:23],
	8:       _fFlagsT_name[23:32],
	16:      _fFlagsT_name[32:40],
	32:      _fFlagsT_name[40:47],
	64:      _fFlagsT_name[47:57],
	128:     _fFlagsT_name[57:67],
	256:     _fFlagsT_name[67:76],
	512:     _fFlagsT_name[76:86],
	1024:    _fFlagsT_name[86:96],
	2048:    _fFlagsT_name[96:106],
	4096:    _fFlagsT_name[106:117],
	8192:    _fFlagsT_name[117:128],
	16384:   _fFlagsT_name[128:137],
	32768:   _fFlagsT_name[137:147],
	65536:   _fFlagsT_name[147:157],
	131072:  _fFlagsT_name[157:164],
	262144:  _fFlagsT_name[164:171],
	524288:  _fFlagsT_name[171:178],
	1048576: _fFlagsT_name[178:183],
}

func (i fFlagsT) String() string {
	if str, ok := _fFlagsT_map[i]; ok {
		return str
	}
	return "fFlagsT(" + strconv.FormatInt(int64(i), 10) + ")"
}
