// Code generated by "stringer -linecomment -type=fFlagsT"; DO NOT EDIT.

package io

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fFile-1]
	_ = x[fDirectory-2]
	_ = x[fSymlink-4]
	_ = x[fDevBlock-8]
	_ = x[fDevChar-16]
	_ = x[fSocket-32]
	_ = x[fNamedPipe-64]
	_ = x[fIrregular-128]
	_ = x[fUserRead-256]
	_ = x[fGroupRead-512]
	_ = x[fOtherRead-1024]
	_ = x[fUserWrite-2048]
	_ = x[fGroupWrite-4096]
	_ = x[fOtherWrite-8192]
	_ = x[fUserExec-16384]
	_ = x[fGroupExec-32768]
	_ = x[fOtherExec-65536]
	_ = x[fSetUid-131072]
	_ = x[fSetGid-262144]
	_ = x[fSticky-524288]
	_ = x[fHelp-1048576]
}

const _fFlagsT_name = "filedirectorysymlinkblock devicecharacter devicesocketnamed pipeirregular fileuser readgroup readothers readuser writegroup writeothers writeuser executegroup executeothers executeset uidset gidsticky bithelp"

var _fFlagsT_map = map[fFlagsT]string{
	1:       _fFlagsT_name[0:4],
	2:       _fFlagsT_name[4:13],
	4:       _fFlagsT_name[13:20],
	8:       _fFlagsT_name[20:32],
	16:      _fFlagsT_name[32:48],
	32:      _fFlagsT_name[48:54],
	64:      _fFlagsT_name[54:64],
	128:     _fFlagsT_name[64:78],
	256:     _fFlagsT_name[78:87],
	512:     _fFlagsT_name[87:97],
	1024:    _fFlagsT_name[97:108],
	2048:    _fFlagsT_name[108:118],
	4096:    _fFlagsT_name[118:129],
	8192:    _fFlagsT_name[129:141],
	16384:   _fFlagsT_name[141:153],
	32768:   _fFlagsT_name[153:166],
	65536:   _fFlagsT_name[166:180],
	131072:  _fFlagsT_name[180:187],
	262144:  _fFlagsT_name[187:194],
	524288:  _fFlagsT_name[194:204],
	1048576: _fFlagsT_name[204:208],
}

func (i fFlagsT) String() string {
	if str, ok := _fFlagsT_map[i]; ok {
		return str
	}
	return "fFlagsT(" + strconv.FormatInt(int64(i), 10) + ")"
}
