// Code generated by "stringer -type=sgrFlag"; DO NOT EDIT.

package virtualterm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[sgrReset-0]
	_ = x[sgrBold-2]
	_ = x[sgrItalic-4]
	_ = x[sgrUnderscore-8]
	_ = x[sgrBlink-16]
	_ = x[sgrFgColour4-32]
	_ = x[sgrFgColour8-64]
	_ = x[sgrFgColour24-128]
	_ = x[sgrBgColour4-256]
	_ = x[sgrBgColour8-512]
	_ = x[sgrBgColour24-1024]
}

const _sgrFlag_name = "sgrResetsgrBoldsgrItalicsgrUnderscoresgrBlinksgrFgColour4sgrFgColour8sgrFgColour24sgrBgColour4sgrBgColour8sgrBgColour24"

var _sgrFlag_map = map[sgrFlag]string{
	0:    _sgrFlag_name[0:8],
	2:    _sgrFlag_name[8:15],
	4:    _sgrFlag_name[15:24],
	8:    _sgrFlag_name[24:37],
	16:   _sgrFlag_name[37:45],
	32:   _sgrFlag_name[45:57],
	64:   _sgrFlag_name[57:69],
	128:  _sgrFlag_name[69:82],
	256:  _sgrFlag_name[82:94],
	512:  _sgrFlag_name[94:106],
	1024: _sgrFlag_name[106:119],
}

func (i sgrFlag) String() string {
	if str, ok := _sgrFlag_map[i]; ok {
		return str
	}
	return "sgrFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
