package docs

//Synonym is used for builtins that might have more than one internal alias
var Synonym map[string]string = map[string]string{
	`!if`:             `if`,
	`!catch`:          `catch`,
	`!global`:         `global`,
	`!set`:            `set`,
	`!and`:            `and`,
	`echo`:            `out`,
	`!or`:             `or`,
	`!export`:         `export`,
	`unset`:           `export`,
	`!event`:          `event`,
	`(`:               `brace-quote`,
	`getfile`:         `getfile`,
	`post`:            `post`,
	`brace-quote`:     `brace-quote`,
	`append`:          `append`,
	`murex-docs`:      `murex-docs`,
	`ttyfd`:           `ttyfd`,
	`rx`:              `rx`,
	`set`:             `set`,
	`err`:             `err`,
	`>`:               `>`,
	`and`:             `and`,
	`if`:              `if`,
	`global`:          `global`,
	`event`:           `event`,
	`get`:             `get`,
	`pt`:              `pt`,
	`trypipe`:         `trypipe`,
	`catch`:           `catch`,
	`export`:          `export`,
	`tout`:            `tout`,
	`f`:               `f`,
	`try`:             `try`,
	`swivel-table`:    `swivel-table`,
	`or`:              `or`,
	`>>`:              `>>`,
	`g`:               `g`,
	`read`:            `read`,
	`prepend`:         `prepend`,
	`swivel-datatype`: `swivel-datatype`,
	`tread`:           `tread`,
	`alter`:           `alter`,
	`out`:             `out`,
}
