// Code generated by "stringer -type=FunctionState"; DO NOT EDIT.

package state

import "strconv"

const _FunctionState_name = "UndefinedMemAllocatedAssignedStartingExecutingExecutedTerminatingAwaitingGCStopped"

var _FunctionState_index = [...]uint8{0, 9, 21, 29, 37, 46, 54, 65, 75, 82}

func (i FunctionState) String() string {
	if i < 0 || i >= FunctionState(len(_FunctionState_index)-1) {
		return "FunctionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FunctionState_name[_FunctionState_index[i]:_FunctionState_index[i+1]]
}
