// Code generated by "stringer -type=FunctionStates"; DO NOT EDIT

package state

import "fmt"

const _FunctionStates_name = "UndefinedMemAllocatedAssignedStartingExecutingExecutedTerminatingAwaitingGC"

var _FunctionStates_index = [...]uint8{0, 9, 21, 29, 37, 46, 54, 65, 75}

func (i FunctionStates) String() string {
	if i < 0 || i >= FunctionStates(len(_FunctionStates_index)-1) {
		return fmt.Sprintf("FunctionStates(%d)", i)
	}
	return _FunctionStates_name[_FunctionStates_index[i]:_FunctionStates_index[i+1]]
}
