// Code generated by "stringer -type=RunMode"; DO NOT EDIT.

package runmode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Default-0]
	_ = x[Normal-1]
	_ = x[BlockUnsafe-2]
	_ = x[FunctionUnsafe-3]
	_ = x[ModuleUnsafe-4]
	_ = x[BlockTry-5]
	_ = x[BlockTryPipe-6]
	_ = x[BlockTryErr-7]
	_ = x[BlockTryPipeErr-8]
	_ = x[FunctionTry-9]
	_ = x[FunctionTryPipe-10]
	_ = x[FunctionTryErr-11]
	_ = x[FunctionTryPipeErr-12]
	_ = x[ModuleTry-13]
	_ = x[ModuleTryPipe-14]
	_ = x[ModuleTryErr-15]
	_ = x[ModuleTryPipeErr-16]
}

const _RunMode_name = "DefaultNormalBlockUnsafeFunctionUnsafeModuleUnsafeBlockTryBlockTryPipeBlockTryErrBlockTryPipeErrFunctionTryFunctionTryPipeFunctionTryErrFunctionTryPipeErrModuleTryModuleTryPipeModuleTryErrModuleTryPipeErr"

var _RunMode_index = [...]uint8{0, 7, 13, 24, 38, 50, 58, 70, 81, 96, 107, 122, 136, 154, 163, 176, 188, 204}

func (i RunMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RunMode_index)-1 {
		return "RunMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunMode_name[_RunMode_index[idx]:_RunMode_index[idx+1]]
}
