// Code generated by "stringer -type=FunctionState"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[FunctionGroup-1]
	_ = x[MemAllocated-2]
	_ = x[Assigned-3]
	_ = x[Starting-4]
	_ = x[Executing-5]
	_ = x[Executed-6]
	_ = x[Terminating-7]
	_ = x[AwaitingGC-8]
	_ = x[Stopped-9]
}

const _FunctionState_name = "UndefinedFunctionGroupMemAllocatedAssignedStartingExecutingExecutedTerminatingAwaitingGCStopped"

var _FunctionState_index = [...]uint8{0, 9, 22, 34, 42, 50, 59, 67, 78, 88, 95}

func (i FunctionState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FunctionState_index)-1 {
		return "FunctionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FunctionState_name[_FunctionState_index[idx]:_FunctionState_index[idx+1]]
}
